"$schema" = 'https://starship.rs/config-schema.json'

format = """
 $os$hostname$username $directory$git_branch [$c$rust$python](color_purple)\
$line_break$character"""

right_format = "$time"

palette = "gruvbox_light"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#fe8019'
color_purple = '#d3869b'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.gruvbox_light]
color_fg0 = '#3c3836'
color_bg1 = '#ebdbb2'
color_bg3 = '#bdae93'
color_blue = '#076678'
color_aqua = '#427b58'
color_green = '#79740e'
color_orange = '#d65d0e'
color_purple = '#8f3f71'
color_red = '#9d0006'
color_yellow = '#b57614'

[aws]
disabled = true

[os]
disabled = false

[os.symbols]
FreeBSD = "[](color_red)"
Windows = "[󰍲](color_blue)"
Ubuntu = "[󰕈](color_orange)"
SUSE = "[](color_green)"
Raspbian = "[󰐿](color_red)"
Mint = "[󰣭](color_green)"
Macos = "󰀵"
Manjaro = "[](color_green)"
Linux = "[󰌽](color_orange)"
Gentoo = "[󰣨](color_purple)"
Fedora = "[󰣛](color_blue)"
Alpine = "[](color_blue)"
Amazon = "[](color_yellow)"
Android = "[](color_green)"
Arch = "[󰣇](color_blue)"
Artix = "[󰣇](color_blue)"
EndeavourOS = "[](color_purple)"
CentOS = "[](color_purple)"
Debian = "[󰣚](color_red)"
Redhat = "[󱄛](color_red)"
RedHatEnterprise = "[󱄛](color_red)"
Pop = "[](color_aqua)"

[hostname]
ssh_only = false
format = '[ $ssh_symbol$hostname]($style)'
style = "color_purple"

[username]
format = '[ $user]($style)'
style_user = "color_blue"
style_root = "color_red"

[directory]
style = "color_orange"
before_repo_root_style = "color_yellow"
repo_root_style = "color_aqua"
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "color_green"
format = '[ $symbol $branch]($style)'

[c]
disabled = true
symbol = " "

[docker_context]
disabled = true

[git_status]
ignore_submodules = true

[rust]
symbol = ""
style = "bg:color_orange"
format = ' $symbol( $version)'

[golang]
symbol = ""
style = "bg:color_orange"
format = ' $symbol( $version)'

[python]
symbol = ""
style = "bg:color_orange"
format = ' $symbol( $version)'

[time]
disabled = false
time_format = "%R"
format = '[  $time ](fg:color_blue)'
